// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/SlashNephy/amq-cache-server/config"
	"github.com/SlashNephy/amq-cache-server/fs"
	"github.com/SlashNephy/amq-cache-server/logging"
	"github.com/SlashNephy/amq-cache-server/repository/external/amq"
	"github.com/SlashNephy/amq-cache-server/usecase/media"
	"github.com/SlashNephy/amq-cache-server/web"
	"github.com/SlashNephy/amq-cache-server/web/controller"
	"github.com/SlashNephy/amq-cache-server/web/middleware/logger"
)

// Injectors from wire.go:

func InitializeServer(ctx context.Context) (*web.Server, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	realFileSystem := fs.NewRealFileSystem()
	client := amq.NewAMQClient()
	mediaService := media.NewMediaService(configConfig, realFileSystem, client)
	controllerController := controller.NewController(mediaService)
	slogLogger, err := logging.NewLogger(configConfig)
	if err != nil {
		return nil, err
	}
	middleware := logger.NewMiddleware(slogLogger)
	server := web.NewServer(configConfig, controllerController, middleware)
	return server, nil
}
